### PR TITLE
[fixes #13] Update plugin to work with phaser versions >= 3.12

### LINKED ISSUE #13: t.save is not a function
Using Phaser 3.12, webpack 4.19.1, and typescript.

This is my code:
```
this.HUDBox = this.add.nineslice(106, 160, // this is the starting x/y location
        HUDwidth, 96, // the width and height of your object
        {
            key: 'levelAtlas',
            frame: 'HUDBox',
        }, // a key to an already loaded image
        9, // the width and height to offset for a corner slice
        8 // (optional) pixels to offset when computing the safe usage area
        );
```

This is the error I get:

```
initFrames
nineslice.js:1 Uncaught TypeError: t.save is not a function
    at i (nineslice.js:1)
    at e.value (nineslice.js:1)
    at e.value (nineslice.js:1)
    at new e (nineslice.js:1)
    at l (nineslice.js:1)
    at GameObjectFactory.value [as nineslice] (nineslice.js:1)
    at FlyerScene.create (flyerScene.ts:52)
    at SceneManager.create (phaser.js:46667)
    at SceneManager.loadComplete (phaser.js:46561)
    at LoaderPlugin.emit (phaser.js:1429)


```

### PR DESCRIPTION
**Pull request by fielding**
## Issue
In Phaser 3.12 RenderTextures were overhauled resulting in this plugin breaking. The matrix-style methods this plugin was using have been removed. You can read more about the specifics of that below in the quoted excerpt from the changelog. I have also included a link to the related dev log.

## Fix
I have updated the code so that for every frame it makes a temporary image via the ObjectCreator, scale the temporary image, draw that to the RenderTexture at the specified location, and finally delete the temporary image.

I'm not sure if this is the desired workaround, but it does seem to work. I have also updated the example.

## Related
- issue #6
- [Phaser 3 Dev Log #125](https://phaser.io/phaser3/devlog/125)
- [Phaser 3 Change Log](https://github.com/photonstorm/phaser/blob/master/CHANGELOG.md)

### CODE REVIEW

**Comment by jdotrjs** [comment]
Thanks for your submission! I'll take a look at this and merge/release today!
